#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-apipkg
Version  : 2.1.1
Release  : 63
URL      : https://files.pythonhosted.org/packages/fb/79/d80c1434167b9d0225237a18abe0c28f222aac58abb37ef9c04f19e85828/apipkg-2.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/fb/79/d80c1434167b9d0225237a18abe0c28f222aac58abb37ef9c04f19e85828/apipkg-2.1.1.tar.gz
Summary  : apipkg: namespace control and lazy-import mechanism
Group    : Development/Tools
License  : MIT
Requires: pypi-apipkg-license = %{version}-%{release}
Requires: pypi-apipkg-python = %{version}-%{release}
Requires: pypi-apipkg-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Welcome to apipkg !
-------------------
With apipkg you can control the exported namespace of a Python package and
greatly reduce the number of imports for your users.
It is a `small pure Python module`_ that works on CPython 2.7 and 3.4+,
Jython and PyPy. It cooperates well with Python's ``help()`` system,
custom importers (PEP302) and common command-line completion tools.

%package license
Summary: license components for the pypi-apipkg package.
Group: Default

%description license
license components for the pypi-apipkg package.


%package python
Summary: python components for the pypi-apipkg package.
Group: Default
Requires: pypi-apipkg-python3 = %{version}-%{release}

%description python
python components for the pypi-apipkg package.


%package python3
Summary: python3 components for the pypi-apipkg package.
Group: Default
Requires: python3-core
Provides: pypi(apipkg)

%description python3
python3 components for the pypi-apipkg package.


%prep
%setup -q -n apipkg-2.1.1
cd %{_builddir}/apipkg-2.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1652105533
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-apipkg
cp %{_builddir}/apipkg-2.1.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-apipkg/82dbfd684f7c04da81d4faa852c6317142daa3e7
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-apipkg/82dbfd684f7c04da81d4faa852c6317142daa3e7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
